name: ERP Postman Automation API Test 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version
      # Runs a single command using the runners shell
      - name: Step 2 Install Newman-Reporter-HtmlExtra
        run: sudo npm install -g newman-reporter-htmlextra

      # Runs a single command using the runners shell
      - name: Step 3 Execute collection
        run: newman run ./AutomacaoPartners.postman_collection.json -e ./Partners.postman_environment.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./docs/index.html

      # - name: Aceita pull resquest se passar no teste
      #   uses: thzois/autobot@v1.0.0
      #   env:
      #     GH_ACCESS_TOKEN: ${{ secrets.RACKATON_TOKEN }}
      #   with:
      #     git_config_user_email: 'pablue@gmail.com'
      #     git_config_user_name: 'Pablo-Oliveira'
      #     target_repo: 'Qa-Coders/new-backend'
      #     source_dir: 'docs/'
      #     source_dir_copy_glob: '!(*.yaml)'
      #     target_dir: ''
      #     pr_target_repo_base_branch: 'develop'
      #     pr_target_repo_compare_branch: 'feature/bugs202309'
      #     pr_title: '[DevOps] [2023-09-091 02:00:00] Automated changes'
      #     pr_description_text: '[DevOps] [2023-09-091 02:00:00] Automated changes'
      #     pr_label: 'Qa.coders_teste_api'


      - name: Merge to Destination Repo
        run: |
          git config --global user.name "Pablo-Oliveira"
          git config --global user.email "pablue@gmail.com"
          git remote add destination https://github.com/Qa-Coders/new-backend
          git fetch destination
          git checkout -b feature/bugs202309  # A branch que será mergeada
          git merge origin/develop  # A branch de origem
          git push destination feature/bugs202309:develop
        env:
          GITHUB_TOKEN: ${{ secrets.RACKATON_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Step 4 Archive Production artifacts
        if: ${{ always() }} # This ensures the step runs even if the previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: ./docs/index.html

      - name: Step 5 Deploy do Report.html
        if: ${{ always() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
